base: 'https://v11.yoast-dev.ddev.site'
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_GB.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-gb
    direction: ltr
    flag: gb
  -
    title: Dutch
    enabled: true
    languageId: 1
    base: 'https://v11-nl.yoast-dev.ddev.site'
    typo3Language: nl
    locale: nl_NL.UTF-8
    iso-639-1: nl
    navigationTitle: Dutch
    hreflang: nl-NL
    direction: ltr
    flag: nl
rootPageId: 1
routes: {  }